my memory is going

diff --git a/new_ports/spaghettikart/spaghettikart/spaghettikart/tools/otrgen b/new_ports/spaghettikart/spaghettikart/spaghettikart/tools/otrgen
--- a/new_ports/spaghettikart/spaghettikart/spaghettikart/tools/otrgen
+++ b/new_ports/spaghettikart/spaghettikart/spaghettikart/tools/otrgen
@@ -43,12 +43,21 @@ process_rom() {
     # Run the extraction
     echo "Extracting data from ../baseroms/$input_file..."
     if ./torch.${DEVICE_ARCH} header -o "../baseroms/$input_file" > /dev/null; then
-        if ./torch.${DEVICE_ARCH} o2r "../baseroms/$input_file" --additional-files meta/mods.toml >> "$LOGFILE"; then
-            echo "[OTRGEN] Extraction complete. O2R generated."
-            mv mk64.o2r ../mk64.o2r
-        else
-            echo "[OTRGEN] Error: O2R generation failed for ../baseroms/$input_file."
-            exit 1
+        # Create zram for torch process if 1GB of ram
+        if [${DEVICE_RAM} eq 1] ; then
+             $ESUDO modprobe zram
+             $ESUDO zramctl --find --size 400M --algorithm lzo
+             $ESUDO mkswap /dev/zram0
+             $ESUDO swapon /dev/zram0 --priority 100
+            if ./torch.${DEVICE_ARCH} o2r "../baseroms/$input_file" --additional-files meta/mods.toml >> "$LOGFILE"; then
+                echo "[OTRGEN] Extraction complete. O2R generated."
+                mv mk64.o2r ../mk64.o2r
+            else
+                echo "[OTRGEN] Error: O2R generation failed for ../baseroms/$input_file."
+                exit 1
+            fi
+            $ESUDO swapoff /dev/zram0
+            $ESUDO zramctl --reset /dev/zram0
         fi
     else
         echo "[OTRGEN] Error: Header extraction failed for ../baseroms/$input_file."
